- name: Install required packages
  apt:
    name:
      - wget
      - tar
    update_cache: yes
    state: present

- name: Add Adoptium GPG key
  ansible.builtin.apt_key:
    url: https://packages.adoptium.net/artifactory/api/gpg/key/public
    state: present

- name: Add Adoptium APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.adoptium.net/artifactory/deb bookworm main"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java 21 JDK
  ansible.builtin.apt:
    name: temurin-21-jdk
    state: present

# kafka user only has permissions on Kafka files and processes; limiting scope of damage to system if caused
- name: Create kafka user
  user:
    name: kafka
    shell: /bin/bash
    create_home: yes

# not from package manager (apt) so no gpg key used. the source was trusted implicitely.
- name: Download Kafka
  get_url:
    url: https://downloads.apache.org/kafka/3.9.1/kafka_2.13-3.9.1.tgz
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
    remote_src: yes
    creates: /opt/kafka_2.13-3.9.1

# Symlink used: If new version installed, link can be changed. system uses /opt/kafka
- name: Symlink Kafka directory
  file:
    src: /opt/kafka_2.13-3.9.1
    dest: /opt/kafka
    state: link
    force: yes

- name: Change ownership of Kafka directory
  file:
    path: /opt/kafka_2.13-3.9.1
    owner: kafka
    group: kafka
    recurse: yes

- name: Copy Zookeeper configuration
  template:
    src: zookeeper.properties.j2
    dest: /opt/kafka/config/zookeeper.properties
    owner: kafka
    group: kafka

- name: Copy Kafka configuration
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
    owner: kafka
    group: kafka

- name: Create systemd unit file for Zookeeper
  copy:
    dest: /etc/systemd/system/zookeeper.service
    content: |
      [Unit]
      Description=Apache Zookeeper
      After=network.target

      [Service]
      Type=simple
      User=kafka
      ExecStart=/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties
      Restart=on-abnormal

      [Install]
      WantedBy=multi-user.target

- name: Create systemd unit file for Kafka
  copy:
    dest: /etc/systemd/system/kafka.service
    content: |
      [Unit]
      Description=Apache Kafka
      After=zookeeper.service

      [Service]
      Type=simple
      User=kafka
      ExecStart=/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
      Restart=on-abnormal

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Zookeeper
  systemd:
    name: zookeeper
    enabled: yes
    state: started

- name: Enable and start Kafka
  systemd:
    name: kafka
    enabled: yes
    state: started
